#ifndef WHISPERS_FACTORTYPES_H
#define WHISPERS_FACTORTYPES_H

enum InternalFactorType {
	AUTHSENSITIVITY, //权威敏感度A
	CONSCIENTIOUSNESS, //学习认真程度B
	WORKLOAD,//工作量Wl
	ENVSENSITIVITY,//环境敏感度E
	SELFCONTROL,//自制力Sc
	INTERNALDRIVE,//内驱力F
	EXTRAVERSION,//外向程度I
};
#endif //WHISPERS_FACTORTYPES_H
